### PR TITLE
Rest API Refactor

### PR DESCRIPTION
**Pull request by csviri**
This should be full compatible with previous version.

### CODE REVIEW

**Comment by csviri** [comment]
Some notes on our API:
- We don't really use HTTP status codes as intended. This would be nice to improve, how the standard defines it.
- For empty list we return something like this: `{"response": "[ ]"}" what is a quoted empty list string. IMO this should be something like this `{"response": [ ] }` not sure what was the intention behind this.

**Review by aptmac — COMMENTED** [review]
> Some notes on our API:
> 
> * We don't really use HTTP status codes as intended. This would be nice to improve, how the standard defines it.  We just re
>   return `{"response": "[error]"}` with 200 status code.

That does make sense, although Ben had mentioned in a comment on an old issue that it might not be as easy as this, other parts of Insights might not be aligned with this change: https://github.com/RedHatInsights/insights-runtimes-inventory/issues/121#issuecomment-1798023415

> * For empty list we return something like this: `{"response": "[ ]"}` what is a quoted empty list string. IMO this should be something like this `{"response": [ ] }` not sure what was the intention behind this.

That would also probably be a nicer change. For reference, the commit before I added these endpoints it returned a string inside of the array braces ([link](https://github.com/RedHatInsights/insights-runtimes-inventory/blame/633c1d718e0a9667acce14fb892998ba49c24635/rest/src/main/java/com/redhat/runtimes/inventory/web/DisplayInventory.java#L72)), so I must have just kept up with the stringification here and returned an empty "[]" instead.

While this PR does look good to me as it stands, shouldn't this PR be opened against the GitLab repository? I didn't think we were continuing development here anymore.

**Comment by csviri** [comment]
@aptmac hmm, yes gitlab repo... totally fogot about that.., that is true I guess

**Comment by csviri** [comment]
moved, will close  the PR here

**Pull request closed without merging**
